services:
  server:
    build:
      context: ./be
      dockerfile: Dockerfile
      target: development
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./be:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - app_network

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5176:5173"
    volumes:
      - ./fe:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app_network
volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
